CREATE TABLE posts.post
(
    id                         BIGSERIAL PRIMARY KEY,
    user_id                    BIGINT       NOT NULL,
    residential_property_id    BIGINT,
    property_legal_document_id BIGINT,
    interior_id                BIGINT,
    house_direction_id         BIGINT,
    balcony_direction_id       BIGINT,
    contact_name               VARCHAR(255) NOT NULL,
    email                      VARCHAR(255),
    phone_number               VARCHAR(12)  NOT NULL,
    demand                     VARCHAR      NOT NULL,
    number_of_bedrooms         INT,
    number_of_bathrooms        INT,
    arena                      DECIMAL(10, 2),
    price                      DECIMAL(15, 2),
    unit                       VARCHAR      NOT NULL,
    description                TEXT,
    image_url                  JSON,
    video_url                  TEXT,
    link_map                   TEXT,
    status                     VARCHAR(50),
    ward_code                  VARCHAR(50),
    district_code              VARCHAR(50),
    province_code              VARCHAR(50),
    street                     VARCHAR(255),
    title                      VARCHAR(255),
    entrance                   DECIMAL(10, 2),
    front                      DECIMAL(10, 2),
    created_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted                 BOOLEAN   DEFAULT FALSE
);
